// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Uply.Infrastructure.Database;

#nullable disable

namespace Uply.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260115205816_GoldAmount")]
    partial class GoldAmount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Uply.Domain.Entities.Roadmap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("Deadline")
                        .HasColumnType("date");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDuo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("IssuerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastRoadmapActivity")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ManHoursPerTask")
                        .HasColumnType("integer");

                    b.Property<int>("Period")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StartingPoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IssuerId");

                    b.ToTable("Roadmap", (string)null);
                });

            modelBuilder.Entity("Uply.Domain.Entities.RoadmapTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoadmapId")
                        .HasColumnType("uuid");

                    b.Property<int>("TaskNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TaskReportId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoadmapId");

                    b.HasIndex("TaskReportId")
                        .IsUnique();

                    b.ToTable("RoadmapTask", (string)null);
                });

            modelBuilder.Entity("Uply.Domain.Entities.TaskReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("PhotoUrls")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("TaskReport", (string)null);
                });

            modelBuilder.Entity("Uply.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("GoldAmount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<long>("TelegramId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("Uply.Domain.Entities.Roadmap", b =>
                {
                    b.HasOne("Uply.Domain.Entities.User", "Issuer")
                        .WithMany("Roadmaps")
                        .HasForeignKey("IssuerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issuer");
                });

            modelBuilder.Entity("Uply.Domain.Entities.RoadmapTask", b =>
                {
                    b.HasOne("Uply.Domain.Entities.Roadmap", "Roadmap")
                        .WithMany("_tasks")
                        .HasForeignKey("RoadmapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Uply.Domain.Entities.TaskReport", "TaskReport")
                        .WithOne("Task")
                        .HasForeignKey("Uply.Domain.Entities.RoadmapTask", "TaskReportId");

                    b.Navigation("Roadmap");

                    b.Navigation("TaskReport");
                });

            modelBuilder.Entity("Uply.Domain.Entities.Roadmap", b =>
                {
                    b.Navigation("_tasks");
                });

            modelBuilder.Entity("Uply.Domain.Entities.TaskReport", b =>
                {
                    b.Navigation("Task")
                        .IsRequired();
                });

            modelBuilder.Entity("Uply.Domain.Entities.User", b =>
                {
                    b.Navigation("Roadmaps");
                });
#pragma warning restore 612, 618
        }
    }
}
